apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue-faas

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: sfbank-blue
  app.kubernetes.io/managed-by: kustomize

images:
  - name: 217350599014.dkr.ecr.ap-northeast-2.amazonaws.com/blue-final-faas-builder
    newTag: latest
