apiVersion: v1
kind: Service
metadata:
  name: blue-faas
  namespace: blue-faas
  labels:
    app.kubernetes.io/name: blue-faas
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: blue-faas
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: 31257
